### ISSUE TITLE
Retry button (WPM) (should-have)

### ISSUE THREAD

**Issue by jeffchen1118** [jeffchen1118/TypeRacer#6]
**User story**

As a user, I want to be able to easily open a new game for another typing speed test so that I can work on improving my typing speed.

**Acceptance Criteria:**

- [x] A newgame button is clearly visible on the web page
- [x] When the newgame button is clicked, a new test is set up at the same difficulty level as the previous one.

**Tasks:**

- [x] Add a "NewGame" button to the typing test.
- [x] Ensure clicking the "NewGame" button resets the test for a new attempt at the same difficulty level as the previous test.
